# Generated by Django 6.0.5 on 2026-05-15 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sns', '0002_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='GachaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('rarity', models.CharField(choices=[('N', 'ノーマル'), ('R', 'レア'), ('SR', '激レア'), ('SSR', '超激レア')], max_length=10)),
                ('image_url', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='items',
            field=models.ManyToManyField(blank=True, to='sns.gachaitem'),
        ),
    ]
