# Generated by Django 6.0.5 on 2026-05-15 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sns', '0003_gachaitem_profile_points_profile_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='current_title',
            field=models.CharField(blank=True, default='新人エンジニア', max_length=100),
        ),
    ]
