# Generated by Django 6.0.5 on 2026-05-16 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sns', '0004_profile_current_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='current_avatar',
            field=models.CharField(blank=True, default='初期アバター', max_length=100),
        ),
    ]
