# Generated by Django 6.0.5 on 2026-05-22 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sns', '0006_post_reply_to_profile_bio_profile_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='subject',
            field=models.CharField(default='その他', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='target_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='target_minutes',
            field=models.IntegerField(default=0),
        ),
    ]
