# Generated by Django 6.0.5 on 2026-06-01 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sns', '0010_user_login_session'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='comment',
            new_name='sns_comment_post_id_fe1e55_idx',
            old_name='sns_comment_post_id_9e78c1_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='sns_notific_recipie_a0b650_idx',
            old_name='sns_notific_recipie_2fd3f1_idx',
        ),
        migrations.RenameIndex(
            model_name='post',
            new_name='sns_post_user_id_6348e7_idx',
            old_name='sns_post_user_id_2eb3c2_idx',
        ),
        migrations.RenameIndex(
            model_name='userloginsession',
            new_name='sns_userlog_user_id_9cff0d_idx',
            old_name='sns_userlog_user_id_46f1fd_idx',
        ),
        migrations.RenameIndex(
            model_name='userloginsession',
            new_name='sns_userlog_logout__0bc5bc_idx',
            old_name='sns_userlog_logout__f93c71_idx',
        ),
        migrations.AddField(
            model_name='profile',
            name='exchange_points',
            field=models.IntegerField(default=0),
        ),
    ]
