# Generated by Django 6.0.5 on 2026-06-11 03:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sns', '0011_rename_sns_comment_post_id_9e78c1_idx_sns_comment_post_id_fe1e55_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'コメント', 'verbose_name_plural': 'コメント'},
        ),
        migrations.AlterModelOptions(
            name='gachaitem',
            options={'verbose_name': 'ガチャアイテム', 'verbose_name_plural': 'ガチャアイテム'},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'verbose_name': '通知', 'verbose_name_plural': '通知'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': '投稿', 'verbose_name_plural': '投稿'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'プロフィール', 'verbose_name_plural': 'プロフィール'},
        ),
        migrations.AlterModelOptions(
            name='userloginsession',
            options={'ordering': ['-login_at'], 'verbose_name': 'ログインセッション', 'verbose_name_plural': 'ログインセッション'},
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='作成日時'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='sns.post', verbose_name='投稿'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(max_length=100, verbose_name='コメント'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー'),
        ),
        migrations.AlterField(
            model_name='gachaitem',
            name='image_url',
            field=models.CharField(blank=True, max_length=200, verbose_name='画像URL'),
        ),
        migrations.AlterField(
            model_name='gachaitem',
            name='name',
            field=models.CharField(max_length=50, verbose_name='名前'),
        ),
        migrations.AlterField(
            model_name='gachaitem',
            name='rarity',
            field=models.CharField(choices=[('N', 'ノーマル'), ('R', 'レア'), ('SR', '激レア'), ('SSR', '超激レア')], max_length=10, verbose_name='レア度'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='作成日時'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='既読'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('like', 'いいね'), ('reply', 'リプライ'), ('follow', 'フォロー')], max_length=20, verbose_name='通知タイプ'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sns.post', verbose_name='関連投稿'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='受信者'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_notifications', to=settings.AUTH_USER_MODEL, verbose_name='送信者'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(max_length=140, verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='作成日時'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.TextField(blank=True, null=True, verbose_name='画像'),
        ),
        migrations.AlterField(
            model_name='post',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='liked_posts', to=settings.AUTH_USER_MODEL, verbose_name='いいねしたユーザー'),
        ),
        migrations.AlterField(
            model_name='post',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='sns.post', verbose_name='リプライ先'),
        ),
        migrations.AlterField(
            model_name='post',
            name='study_minutes',
            field=models.IntegerField(default=0, verbose_name='勉強時間(分)'),
        ),
        migrations.AlterField(
            model_name='post',
            name='subject',
            field=models.CharField(default='その他', max_length=50, verbose_name='科目'),
        ),
        migrations.AlterField(
            model_name='post',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='自己紹介'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='current_avatar',
            field=models.CharField(blank=True, default='初期アバター', max_length=100, verbose_name='現在のアバター'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='current_title',
            field=models.CharField(blank=True, default='新人エンジニア', max_length=100, verbose_name='現在の称号'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='department',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='部署'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='display_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='表示名'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='exchange_points',
            field=models.IntegerField(default=0, verbose_name='交換ポイント'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='follows',
            field=models.ManyToManyField(blank=True, related_name='followed_by', to='sns.profile', verbose_name='フォロー'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='icon',
            field=models.TextField(blank=True, null=True, verbose_name='アイコン'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='items',
            field=models.ManyToManyField(blank=True, to='sns.gachaitem', verbose_name='所持アイテム'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='points',
            field=models.IntegerField(default=0, verbose_name='ポイント'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='target_date',
            field=models.DateField(blank=True, null=True, verbose_name='目標日'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='target_minutes',
            field=models.IntegerField(default=0, verbose_name='目標時間(分)'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='theme_color',
            field=models.CharField(default='dark', max_length=20, verbose_name='テーマカラー'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー'),
        ),
        migrations.AlterField(
            model_name='userloginsession',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IPアドレス'),
        ),
        migrations.AlterField(
            model_name='userloginsession',
            name='last_seen_at',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='最終アクセス日時'),
        ),
        migrations.AlterField(
            model_name='userloginsession',
            name='login_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='ログイン日時'),
        ),
        migrations.AlterField(
            model_name='userloginsession',
            name='logout_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='ログアウト日時'),
        ),
        migrations.AlterField(
            model_name='userloginsession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_sessions', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー'),
        ),
        migrations.AlterField(
            model_name='userloginsession',
            name='user_agent',
            field=models.TextField(blank=True, verbose_name='ユーザーエージェント'),
        ),
    ]
