# Generated by Django 6.0.5 on 2026-06-11 05:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sns", "0012_alter_comment_options_alter_gachaitem_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="image_file",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="post_images/",
                verbose_name="画像(ファイル)",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="icon_file",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="profile_icons/",
                verbose_name="アイコン(ファイル)",
            ),
        ),
    ]
