# Generated by Django 6.0.5 on 2026-06-14 05:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sns", "0014_migrate_base64_to_cloudinary"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="consecutive_post_days",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="profile",
            name="last_post_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
